spring.application.name: app
# https://www.devglan.com/online-tools/hmac-sha256-online
security.jwt.secret-key: deff1af56cce746d7cd3eeef041e4938b11dd214b7bfa97357f9217a3ab2909e
# 1h in millisecond
security.jwt.expiration-time: 3600000

# 30 days in milliseconds
security.refresh-token.expiration-time: 2592000000

logging.level.root: DEBUG

spring:
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

