workflows:
  build-and-deploy:
    jobs:
      - test-frontend
      - test-backend
version: 2.1
jobs:
  test-frontend:
    working_directory: ~/bookkeeper/src/main/front/
    docker:
      - image: node:22.0.0-alpine
    steps:
      - checkout:
          path:  ~/bookkeeper
      - run:
          name: "Build"
          command: npm run build
      - run:
          name: "Tests"
          command: npm test
      - save_cache:
          paths:
            - ~/src/main/front/node_modules
          key: v1-node-modules-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
  test-backend:
    working_directory: ~/bookkeeper
    docker:
      - image: openjdk:23-jdk
    steps:
      - run:
          name: "Build"
          command: ./gradlew clean build
      - run:
          name: "Tests"
          command: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - build