### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test1"
}

> {% client.global.set("jwt_token", response.body.jwtToken.token); %}
> {% client.global.set("refresh_token", response.body.refreshToken.token); %}

### list events
GET http://localhost:8080/events
Authorization: Bearer {{jwt_token}}

### logout
GET http://localhost:8080/auth/logout
Authorization: Bearer {{jwt_token}}

### refresh token
POST http://localhost:8080/auth/refreshToken
Content-Type: application/json

{
    "refreshToken": "70fbcb20-3e40-4a5c-ac6f-2d9170a69f07"
}